# Generated by Django 3.1.3 on 2021-01-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210117_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='category',
            new_name='cat',
        ),
    ]
