# Generated by Django 3.1.3 on 2021-01-17 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210117_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auctionBid', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidAmt',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bid',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
